version: '3'

services:
  medications-api:
    build: ./healthcare-medications-server
    ports:
    - "3002:3002"
    command: npm run start
    volumes:
    - ./healthcare-medications-server:/app
    - /app/node_modules
    depends_on:
    - postgres-medications

  nest-api:
    build: ./healthcare-api
    ports:
      - "3000:3000"
    command: npm run start:dev
    volumes:
      - ./healthcare-api:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  redis-micro:
    build: ./healthcare-redis
    command: npm start
    volumes:
    - ./healthcare-redis:/app
    - /app/node_modules
    depends_on:
    - redis

  postgres:
    image: postgres
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=healthcare

  postgres-medications:
    image: postgres
    ports:
    - "5001:5432"
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=medications

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./healthcare-frontend
      args:
        - NODE_ENV=development
    ports:
      - "1233:1233"
      - "1234:1234"
      - "3001:3001"
      - "38771:38771"
    command: npm start
    volumes:
      - ./healthcare-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - nest-api
